---
title: "DSE3101_Lecture 2"
author: Zitin Bali
date: "2024-01-26"
output: 
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6
  
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/zitinbali/Desktop/DSE3101/Coding/Lecture 2")

```


```{r libraries, message = FALSE}

library(tidyverse)

```

## Statistics on Returns

```{r read}

stocks <- readRDS('./wk2_stocks.rds')

cumulative_returns = sum(stocks$SPY_returns)*100
ave_daily_returns = mean(stocks$SPY_returns)*100
std_dev = sd(stocks$SPY_returns)*100

```

+ The cumulative returns of the S&P index during this period is `r round(cumulative_returns, 2)`%.

+ The average daily returns of the S&P index during this period is `r round(ave_daily_returns, 2)`%.

+ The standard deviation of the daily returns of the S&P index during this period is `r round(std_dev, 2)`%.


## S&P Prices

```{r plot1}

ggplot(data = stocks, aes(x = date, y = SPY_prices)) +
  geom_line(data = stocks, aes(x = date, y = SPY_prices))

```

## S&P Yearly Returns

```{r plot2}

stocks %>%
  mutate(year = year(date)) %>%
  filter(year <= 2023) %>%
  group_by(year) %>%
  summarise(yr_return = sum(SPY_returns)) %>%
  ggplot(aes(x = year, y = yr_return)) + 
  geom_col()

```

